spring:
  datasource:
      url: jdbc:mysql://localhost:3306/dbspotmusic?useSSL=false&createDatabaseIfNotExist=true
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
      show_sql: true
      auto: update